site_name: n0signal Â· 0xkb
site_url: https://Kaninte.github.io/0xkb/

theme:
  name: dracula
  sidebar: true
  navigation_depth: 2
  components:
    footer: false
    title: false
  favicon: assets/favicon.ico
  logo: assets/logo.png

markdown_extensions:
  - admonition
  - nl2br 
  - toc:
      permalink: false
nav:
  - Home: index.md
  - OS:
      - "Microsoft Install": os_install_microsoft.md
  - LLM:
      - "LLM Jailbreaking": llm_jailbreaking.md
      - "LLM Gandalf": llm_gandalf.md
extra_css:
  - assets/heading-fix.css
  - assets/blacksite.css
